# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: jsonparse-release-docker

on:
  release:
    types: [published]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Google Container Registry
        shell: bash
        run: |
          docker login -u _json_key -p '${{ secrets.GCP_SERVICE_ACCOUNT }}' 'https://gcr.io' 2>/dev/null
          docker tag '${{ inputs.source_image }}' '${{ inputs.destination_image }}'
          docker push '${{ inputs.destination_image }}'
          echo "Successfully pushed ${{ inputs.source_image }} to ${{ inputs.destination_image }}"
      -
        name: Build and push to dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: VERSION=${{ github.ref_name }}
          tags: |
            ctomkow/jsonparse:${{ github.ref_name }}
            ctomkow/jsonparse:latest
            gcr.io/jsonparse-363219/ctomkow/jsonparse:${{ github.ref_name }}
            gcr.io/jsonparse-363219/ctomkow/jsonparse:latest
