# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: jsonparse-release-docker

on:
  release:
    types: [published]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ctomkow/jsonparse:${{ github.ref_name }},ctomkow/jsonparse:latest
          build-args: VERSION=${{ github.ref_name }}
      -
        name: push to google compute registry
        uses: Dayanand-Chinchure/gcr-upload-action@1.2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          source_image: ctomkow/jsonparse:${{ github.ref_name }}
          destination_image: gcr.io/jsonparse-363219/jsonparse:${{ github.ref_name }}
